build:
	dotnet build

run:
	dotnet run

clean:
	dotnet clean

restore:
	dotnet restore

publish:
	dotnet publish -c Release

test:
	dotnet test

test-coverage:
	dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/coverage-results